# Generated by Django 5.1.3 on 2025-02-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_alter_question_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.JSONField(verbose_name='정답'),
        ),
    ]
