# Generated by Django 5.1.3 on 2024-12-29 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam_app', '0001_initial'),
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OMRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(verbose_name='시험 날짜')),
                ('teacher_code', models.CharField(max_length=2, verbose_name='강사코드')),
                ('exam_identifier', models.CharField(blank=True, max_length=8, null=True, verbose_name='시험식별자')),
                ('is_matched', models.BooleanField(default=False, verbose_name='매칭 여부')),
                ('unmatched_student_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='미매칭 학생코드')),
                ('unmatched_student_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='미매칭 학생이름')),
                ('answer_sheet', models.ImageField(upload_to='answer_sheets/', verbose_name='답안지')),
                ('processed_sheet', models.ImageField(blank=True, null=True, upload_to='processed_sheets/', verbose_name='처리된 답안지')),
                ('answers', models.JSONField(verbose_name='답안 결과')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('class_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='반이름')),
                ('omr_name', models.CharField(blank=True, default='', max_length=50, verbose_name='OMR 이름')),
                ('exam_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omr_results', to='exam_app.examsheet', verbose_name='시험지')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_app.student')),
            ],
            options={
                'verbose_name': 'OMR 결과',
                'verbose_name_plural': 'OMR 결과들',
            },
        ),
    ]
