# Generated by Django 5.1.3 on 2025-02-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omrstudentanswer',
            name='score_earned',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='획득 점수'),
        ),
    ]
