# Generated by Django 5.1.3 on 2025-01-01 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OMRResultEssayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(verbose_name='주관식 문항 번호')),
                ('image', models.ImageField(upload_to='essay_images/', verbose_name='주관식 문항 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('omr_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_images', to='omr_app.omrresult', verbose_name='OMR 결과')),
            ],
        ),
    ]
