# Generated by Django 5.1.3 on 2025-01-04 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
        ('omr_app', '0002_omrresultessayimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OMRStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answers', models.JSONField(blank=True, null=True, verbose_name='선택한 답')),
                ('is_correct', models.BooleanField(default=False, verbose_name='정답 여부')),
                ('score_earned', models.FloatField(default=0.0, verbose_name='획득 점수')),
                ('total_score', models.FloatField(default=1.0, verbose_name='배점')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('omr_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='omr_app.omrresult')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='exam_app.question')),
            ],
            options={
                'verbose_name': '학생-문항별 응답',
                'verbose_name_plural': '학생-문항별 응답(OMRStudentAnswer)',
                'unique_together': {('omr_result', 'question')},
            },
        ),
    ]
