# Generated by Django 5.1.3 on 2025-02-08 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_alter_question_answer'),
        ('omr_app', '0002_alter_omrstudentanswer_score_earned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omrresult',
            name='exam_sheet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omr_results', to='exam_app.examsheet', verbose_name='시험지'),
        ),
    ]
