# Generated by Django 5.1.3 on 2025-01-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0003_omrstudentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrresult',
            name='front_page',
            field=models.ImageField(blank=True, null=True, upload_to='omr_front_pages/', verbose_name='OMR 앞면 이미지'),
        ),
    ]
