# Generated by Django 5.1.3 on 2025-02-08 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0003_alter_omrresult_exam_sheet'),
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omrresult',
            name='is_matched',
        ),
        migrations.AlterField(
            model_name='omrresult',
            name='student',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_app.student'),
        ),
    ]
