# Generated by Django 5.1.3 on 2025-02-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0004_remove_omrresult_is_matched_alter_omrresult_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrresult',
            name='is_graded',
            field=models.BooleanField(default=False, verbose_name='채점 완료 여부'),
        ),
    ]
