# Generated by Django 5.1.3 on 2025-02-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0005_omrresult_is_graded'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrresult',
            name='total_score_earned',
            field=models.FloatField(default=0, verbose_name='총 획득 점수'),
        ),
        migrations.AddField(
            model_name='omrresult',
            name='total_score_possible',
            field=models.FloatField(default=0, verbose_name='총 배점'),
        ),
    ]
