# Generated by Django 5.1.3 on 2025-02-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0006_omrresult_total_score_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrresult',
            name='voca_score_earned',
            field=models.FloatField(default=0, verbose_name='어휘 획득 점수'),
        ),
        migrations.AddField(
            model_name='omrresult',
            name='voca_score_possible',
            field=models.FloatField(default=0, verbose_name='어휘 배점'),
        ),
    ]
