# Generated by Django 5.1.3 on 2024-12-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OMRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(verbose_name='시험 날짜')),
                ('class_code', models.CharField(max_length=2, verbose_name='반 코드')),
                ('student_id', models.CharField(max_length=8, verbose_name='학번')),
                ('student_name', models.CharField(max_length=10, verbose_name='이름')),
                ('answer_sheet', models.ImageField(upload_to='answer_sheets/', verbose_name='답안지')),
                ('processed_sheet', models.ImageField(blank=True, null=True, upload_to='processed_sheets/', verbose_name='처리된 답안지')),
                ('answers', models.JSONField(verbose_name='답안 결과')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': 'OMR 결과',
                'verbose_name_plural': 'OMR 결과들',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='학번')),
                ('registration_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='등록번호')),
                ('registered_date', models.DateTimeField(blank=True, null=True, verbose_name='등록일')),
                ('name', models.CharField(max_length=10, verbose_name='이름')),
                ('class_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='소속반')),
                ('school_type', models.CharField(blank=True, choices=[('M', '중학교'), ('H', '고등학교')], max_length=1, null=True, verbose_name='중/고등 구분')),
                ('school_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='학교명')),
                ('grade', models.IntegerField(blank=True, choices=[(1, '1학년'), (2, '2학년'), (3, '3학년')], null=True, verbose_name='학년')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='본인 연락처')),
                ('parent_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='보호자 연락처')),
                ('note', models.TextField(blank=True, null=True, verbose_name='비고')),
            ],
            options={
                'verbose_name': '학생',
                'verbose_name_plural': '학생들',
            },
        ),
    ]
