# Generated by Django 5.1.3 on 2024-12-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OMRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(verbose_name='시험 날짜')),
                ('class_code', models.CharField(max_length=2, verbose_name='반 코드')),
                ('student_id', models.CharField(max_length=8, verbose_name='학번')),
                ('student_name', models.CharField(max_length=10, verbose_name='이름')),
                ('answer_sheet', models.ImageField(upload_to='answer_sheets/', verbose_name='답안지')),
                ('processed_sheet', models.ImageField(blank=True, null=True, upload_to='processed_sheets/', verbose_name='처리된 답안지')),
                ('answers', models.JSONField(verbose_name='답안 결과')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': 'OMR 결과',
                'verbose_name_plural': 'OMR 결과들',
            },
        ),
    ]
