# Generated by Django 5.1.3 on 2024-12-05 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='omrresult',
            old_name='student_id',
            new_name='student_code',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='student_code',
        ),
    ]
