# Generated by Django 5.1.3 on 2024-12-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='학번')),
                ('registered_date', models.DateField(auto_now_add=True, verbose_name='등록일')),
                ('name', models.CharField(max_length=10, verbose_name='이름')),
                ('class_name', models.CharField(max_length=20, verbose_name='소속반')),
                ('school_type', models.CharField(choices=[('M', '중학교'), ('H', '고등학교')], max_length=1, verbose_name='중/고등 구분')),
                ('grade', models.IntegerField(choices=[(1, '1학년'), (2, '2학년'), (3, '3학년')], verbose_name='학년')),
                ('school_name', models.CharField(max_length=30, verbose_name='학교명')),
                ('phone_number', models.CharField(max_length=11, verbose_name='본인 연락처')),
                ('parent_phone', models.CharField(max_length=11, verbose_name='보호자 연락처')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
            ],
            options={
                'verbose_name': '학생',
                'verbose_name_plural': '학생들',
            },
        ),
    ]
