# Generated by Django 5.1.3 on 2024-12-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0002_rename_student_id_omrresult_student_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
