# Generated by Django 5.1.3 on 2024-12-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0004_question_examsheet_examsheetquestionmapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrresult',
            name='is_matched',
            field=models.BooleanField(default=False, verbose_name='매칭 여부'),
        ),
        migrations.AddField(
            model_name='omrresult',
            name='unmatched_student_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='미매칭 학생코드'),
        ),
    ]
