# Generated by Django 5.1.3 on 2024-12-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0006_omrresult_unmatched_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omrresult',
            name='class_code',
        ),
        migrations.AddField(
            model_name='omrresult',
            name='exam_identifier',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='시험식별자'),
        ),
        migrations.AddField(
            model_name='omrresult',
            name='exam_order',
            field=models.CharField(default=4, max_length=2, verbose_name='시험 순번'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='omrresult',
            name='temp_exam_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='임시 시험명'),
        ),
    ]
