# Generated by Django 5.1.3 on 2024-12-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0007_remove_omrresult_class_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omrresult',
            name='exam_order',
        ),
        migrations.AddField(
            model_name='omrresult',
            name='teacher_code',
            field=models.CharField(default=1, max_length=2, verbose_name='강사코드'),
            preserve_default=False,
        ),
    ]
