# Generated by Django 5.1.3 on 2024-12-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0009_alter_omrresult_exam_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrresult',
            name='exam_sheet_matched',
            field=models.BooleanField(default=False, verbose_name='문제지 매칭 여부'),
        ),
    ]
