# Generated by Django 5.1.3 on 2024-12-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0010_omrresult_exam_sheet_matched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omrresult',
            name='temp_exam_name',
        ),
        migrations.AddField(
            model_name='omrresult',
            name='class_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='반이름'),
        ),
        migrations.AddField(
            model_name='omrresult',
            name='exam_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='시험명'),
        ),
    ]
