# Generated by Django 5.1.3 on 2024-12-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0011_remove_omrresult_temp_exam_name_omrresult_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_name_by_school',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='내신반'),
        ),
    ]
