# Generated by Django 5.1.3 on 2024-12-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0013_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status_changed_date',
            field=models.DateField(blank=True, null=True, verbose_name='상태변경일'),
        ),
    ]
