# Generated by Django 5.1.3 on 2024-12-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0014_student_status_changed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status_reason',
            field=models.TextField(blank=True, null=True, verbose_name='상태변경사유'),
        ),
    ]
