# Generated by Django 5.1.3 on 2024-12-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0016_remove_omrresult_exam_name_omrresult_omr_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omrresult',
            name='omr_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='OMR 이름'),
        ),
    ]
