# Generated by Django 5.1.3 on 2024-12-11 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0017_alter_omrresult_omr_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omrresult',
            name='exam_sheet_matched',
        ),
        migrations.AddField(
            model_name='omrresult',
            name='exam_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omr_results', to='omr_app.examsheet', verbose_name='시험지'),
        ),
    ]
