# Generated by Django 5.1.3 on 2024-12-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0018_remove_omrresult_exam_sheet_matched_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impliedmeaningquestion',
            name='question_ptr',
        ),
        migrations.RemoveField(
            model_name='sentenceinsertquestion',
            name='question_ptr',
        ),
        migrations.RemoveField(
            model_name='sequenceorderquestion',
            name='question_ptr',
        ),
        migrations.RemoveField(
            model_name='summaryquestion',
            name='question_ptr',
        ),
        migrations.RemoveField(
            model_name='themequestion',
            name='question_ptr',
        ),
        migrations.RemoveField(
            model_name='titlequestion',
            name='question_ptr',
        ),
        migrations.RemoveField(
            model_name='vocaincontextquestion',
            name='question_ptr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_5',
        ),
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, choices=[('단어', '단어'), ('어법', '어법'), ('독해', '독해')], max_length=10, null=True, verbose_name='구분'),
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='보기'),
        ),
        migrations.AddField(
            model_name='question',
            name='detail_type',
            field=models.CharField(blank=True, choices=[('객관식_어법', '객관식 어법'), ('논술형_어법', '논술형 어법'), ('순서배열', '순서배열'), ('문장삽입', '문장삽입'), ('제목', '제목'), ('주제', '주제'), ('요약문', '요약문'), ('빈칸추론', '빈칸추론'), ('함축의미', '함축의미'), ('문맥어휘', '문맥어휘'), ('영영풀이', '영영풀이')], max_length=20, null=True, verbose_name='상세유형'),
        ),
        migrations.AddField(
            model_name='question',
            name='evaluation_area',
            field=models.CharField(blank=True, choices=[('단어', '단어'), ('어법', '어법'), ('글의_흐름_파악', '글의 흐름 파악'), ('핵심_내용', '핵심 내용'), ('논리적_추론', '논리적 추론'), ('어휘', '어휘')], max_length=20, null=True, verbose_name='평가영역'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_format',
            field=models.CharField(choices=[('MC', '객관식'), ('SA', '논술형')], default='MC', max_length=2, verbose_name='답안형식'),
        ),
        migrations.DeleteModel(
            name='BlankInferenceQuestion',
        ),
        migrations.DeleteModel(
            name='ImpliedMeaningQuestion',
        ),
        migrations.DeleteModel(
            name='SentenceInsertQuestion',
        ),
        migrations.DeleteModel(
            name='SequenceOrderQuestion',
        ),
        migrations.DeleteModel(
            name='SummaryQuestion',
        ),
        migrations.DeleteModel(
            name='ThemeQuestion',
        ),
        migrations.DeleteModel(
            name='TitleQuestion',
        ),
        migrations.DeleteModel(
            name='VocaInContextQuestion',
        ),
    ]
