# Generated by Django 5.1.3 on 2024-12-12 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0019_remove_impliedmeaningquestion_question_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
        migrations.AddField(
            model_name='question',
            name='is_double_question',
            field=models.BooleanField(default=False, verbose_name='2문제 여부'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_1',
            field=models.TextField(default='', verbose_name='발문1'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_2',
            field=models.TextField(blank=True, null=True, verbose_name='발문2'),
        ),
        migrations.CreateModel(
            name='AnswerField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_group', models.IntegerField(default=1, verbose_name='작성란 그룹')),
                ('text_format', models.TextField(verbose_name='작성란 형식')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_fields', to='omr_app.question')),
            ],
            options={
                'verbose_name': '답안 작성란',
                'verbose_name_plural': '답안 작성란들',
                'ordering': ['field_group', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_group', models.IntegerField(default=1, verbose_name='테이블 그룹')),
                ('title', models.CharField(max_length=200, verbose_name='표 제목')),
                ('content', models.TextField(verbose_name='표 내용')),
                ('table_type', models.CharField(choices=[('CONDITION', '조건'), ('EXAMPLE', '보기'), ('SUMMARY', '요약문')], max_length=10, verbose_name='표 유형')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='omr_app.question')),
            ],
            options={
                'verbose_name': '문제 테이블',
                'verbose_name_plural': '문제 테이블들',
                'ordering': ['table_group', 'table_type'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_group', models.IntegerField(default=1, verbose_name='보기 그룹')),
                ('choice_number', models.IntegerField(verbose_name='보기 번호')),
                ('text_content', models.TextField(verbose_name='텍스트 내용')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='omr_app.question')),
            ],
            options={
                'verbose_name': '보기',
                'verbose_name_plural': '보기들',
                'ordering': ['choice_group', 'choice_number'],
                'unique_together': {('question', 'choice_group', 'choice_number')},
            },
        ),
    ]
