# Generated by Django 5.1.3 on 2024-12-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0020_remove_question_choices_question_is_double_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='detail_type',
        ),
        migrations.RemoveField(
            model_name='questiontable',
            name='title',
        ),
        migrations.AddField(
            model_name='question',
            name='detail_type_1',
            field=models.CharField(blank=True, choices=[('객관식_어법', '객관식 어법'), ('논술형_어법', '논술형 어법'), ('순서배열', '순서배열'), ('문장삽입', '문장삽입'), ('제목', '제목'), ('주제', '주제'), ('요약문', '요약문'), ('빈칸추론', '빈칸추론'), ('함축의미', '함축의미'), ('문맥어휘', '문맥어휘'), ('영영풀이', '영영풀이')], max_length=20, null=True, verbose_name='상세유형1'),
        ),
        migrations.AddField(
            model_name='question',
            name='detail_type_2',
            field=models.CharField(blank=True, choices=[('객관식_어법', '객관식 어법'), ('논술형_어법', '논술형 어법'), ('순서배열', '순서배열'), ('문장삽입', '문장삽입'), ('제목', '제목'), ('주제', '주제'), ('요약문', '요약문'), ('빈칸추론', '빈칸추론'), ('함축의미', '함축의미'), ('문맥어휘', '문맥어휘'), ('영영풀이', '영영풀이')], max_length=20, null=True, verbose_name='상세유형2'),
        ),
        migrations.AddField(
            model_name='question',
            name='double_question_label',
            field=models.CharField(blank=True, help_text='예: 다음 글을 읽고 물음에 답하시오.', max_length=100, null=True, verbose_name='지문 라벨'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, choices=[('단어', '단어'), ('어법', '어법'), ('독해', '독해'), ('복합', '복합')], max_length=10, null=True, verbose_name='구분'),
        ),
    ]
