# Generated by Django 5.1.3 on 2024-12-25 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0021_remove_question_detail_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_source', models.CharField(blank=True, help_text='원본을 명시하고 싶을 경우.', max_length=200, null=True, verbose_name='지문출처')),
                ('passage_text', models.TextField(blank=True, null=True, verbose_name='지문 내용')),
                ('passage_table', models.TextField(blank=True, null=True, verbose_name='지문 표(HTML)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
        ),
        migrations.AlterModelOptions(
            name='answerfield',
            options={'verbose_name': '답안 작성란', 'verbose_name_plural': '답안 작성란들'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['choice_number'], 'verbose_name': '보기', 'verbose_name_plural': '보기들'},
        ),
        migrations.AlterModelOptions(
            name='questiontable',
            options={'ordering': ['order'], 'verbose_name': '문제 테이블', 'verbose_name_plural': '문제 테이블들'},
        ),
        migrations.RemoveField(
            model_name='answerfield',
            name='field_group',
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('question', 'choice_number')},
        ),
        migrations.RemoveField(
            model_name='examsheet',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='examsheet',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='detail_type_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='detail_type_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='double_question_label',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_double_question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='original_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text_2',
        ),
        migrations.RemoveField(
            model_name='questiontable',
            name='table_group',
        ),
        migrations.RemoveField(
            model_name='questiontable',
            name='table_type',
        ),
        migrations.AddField(
            model_name='originaltext',
            name='text_source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='원문 출처'),
        ),
        migrations.AddField(
            model_name='question',
            name='detail_type',
            field=models.CharField(blank=True, choices=[('객관식_어법', '객관식 어법'), ('논술형_어법', '논술형 어법'), ('순서배열', '순서배열'), ('문장삽입', '문장삽입'), ('제목', '제목'), ('주제', '주제'), ('요약문', '요약문'), ('빈칸추론', '빈칸추론'), ('함축의미', '함축의미'), ('문맥어휘', '문맥어휘'), ('영영풀이', '영영풀이')], max_length=20, null=True, verbose_name='상세유형'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(default='', verbose_name='발문'),
        ),
        migrations.AddField(
            model_name='questiontable',
            name='order',
            field=models.IntegerField(default=1, verbose_name='순서'),
        ),
        migrations.AddField(
            model_name='question',
            name='passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='omr_app.passage', verbose_name='연결된 지문'),
        ),
        migrations.CreateModel(
            name='PassageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_group', models.IntegerField(default=1, verbose_name='테이블 그룹')),
                ('content', models.TextField(verbose_name='표 내용')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='omr_app.passage')),
            ],
            options={
                'verbose_name': '지문 테이블',
                'verbose_name_plural': '지문 테이블들',
                'ordering': ['table_group'],
            },
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_group',
        ),
    ]
